#!/usr/bin/env bash

current_branch=$(git symbolic-ref --short HEAD)

files_changed_amount=$(git status --short | wc -l)
if [ "$current_branch" == "master" ] && [ "$files_changed_amount" != "0" ]
then
        >&2 echo "There are uncommitted changes!"
        exit 1
fi